# .github/workflows/chromatic.yml

# Workflow name
name: 🖼️ Chromatic - Storybook

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    env:
      ENVKEY: ${{ secrets.ENVKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # 👇 Fetches the full history of the repository
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set pnpm config to prefer offline
        run: pnpm config set prefer-offline true

      - name: Install dependencies
        run: pnpm install

      - name: Post Cache step
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: Installing envkey-source 
        run: ./scripts/env-checks/gh/actions_installer.sh || true
        
      - name: Load Envkey vars, Display Value for Z_ENVKEY_TEST_VAR
        run: |
          echo "$Z_ENVKEY_TEST_VAR"

      - name: Publish to Chromatic
        run: pnpm run chromatic --exit-once-uploaded
